---
 - name: create directory and copy file to mumbai dc rhel servers
   hosts: all
   tasks:
    
    - name: create a directory
      file:
       path: /common
       state: directory

    - name: copy a file
      copy:
       src: ../files/file1
       dest: /common
...
