---
 - name: implement apache web server in mumbai dc rhel servers
   hosts: rhel
   tasks:

    - name: install apache software
      dnf:
        name: httpd
        state: present

    - name: start and enable apache service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: install firewalld software
      dnf:
        name: firewalld
        state: present

    - name: start and enable firewalld service
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: allow http traffic via firewalld
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
...
