---
 - name: copy site1 to rhel server1
   hosts: ec2-13-126-236-181.ap-south-1.compute.amazonaws.com
   tasks:
    
    - name: copy site1
      copy:
        src: ../files/site1
        dest: /var/www/html
 
 - name: copy site2 to rhel server2
   hosts: 35.154.241.162
   tasks:
    
    - name: copy site2
      copy:
        src: ../files/site2
        dest: /var/www/html
...
