---
 - name: create users in mumbai servers
   hosts: all
   gather_facts: no
   tasks:
    
    - name: create user1
      user:
        name: '{{item}}'
        state: present
      loop:
       - user1
       - user2
       - user3
       - user4
       - user5


